= Forecast of response
:toc:
:icons: font
:hide-uri-scheme:

== Introduction

Use weather forecasts and numerical models to find out and forecast the vertical movement on ships, so that it is possible to provide better decision support for those on board ships.

The application uses https://www.sintef.no/ocean/programvare/[sima or simpos] for numerical calculations,
and should support different type of marine operations (different Sima models).

=== Success criteria

* Flexible dashboard that can support and show many different numerical outputs
* Flexible numerial engine that can support many numerical models

=== Level 1 - System Context diagram

The Context diagram is a good starting point for diagramming and documenting a software system, allowing you to step back and see the big picture. Here we draw a diagram showing the system as a box in the centre, surrounded by its users and the other systems that it interacts with.

[plantuml,,svg]
....
@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

LAYOUT_WITH_LEGEND()

Person(offshore_users, "Offshore User", "A user that wants to monitor the vertical movement onboard ships.")
Person(domain_expert_users, "Domain Expert User", "A user that wants to interface and upload numerical models.")

System(app, "Forecast of Response System", "A system that use weather forecasts and numerical models to find out and forecast the vertical movement on ships, so that it is possible to provide better decision support for those on board ships.")

System_Ext(sima, "Sima", "Numerical engine")

Rel(domain_expert_users, app, "Uses")
Rel(offshore_users, app, "Uses")

Rel(app, sima, "Run simulations")

@enduml
....

=== Level 2 - Container diagram
Once you understand how your system fits in to the overall IT environment, a really useful next step is to zoom-in to the system boundary with a Container diagram. A container is something like a server-side web application, single-page application, desktop application, mobile app, database schema, file system, etc. Essentially, a container is a separately runnable/deployable unit (e.g. a separate process space) that executes code or stores data.

==== No Data Modelling Tool

[plantuml,,svg]
....
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
LAYOUT_WITH_LEGEND()

Container_Ext(auth, "Authentication","Azure AD Auth service")
Container_Ext(environment, "Environment Source", "")
Container_Ext(models, "Model Source", "")
Container_Ext(tasks, "SIMA Task Source", "")

Boundary(radix, "Radix", "Equinor PaaS"){
    Container(web, "WebApp", "React SPA", "Login with a role('Forcaster' or 'User') which grants different views")
    Container(api, "API", "Python rest API", "API for CRUD operations as well as scheduling SIMA tasks")
    Container_Ext(simaservice, "SIMA Runtime Service", "", "Azure AD Login with a role('Forcaster' or 'User') which grants different views")
}

ContainerDb(storage, "Storage", "SQL/NoSQL/BLOB", "workflows, models, and results")
Container_Ext(email, "Email Service", "","Used to notify users of completed long-running tasks")

Rel(environment, web, "Uploads")
Rel(models, web, "Uploads")
Rel(tasks, web, "Uploads")
Rel(web, api, "HTTP")
Rel(api, simaservice, "Starts tasks and fetches results (gRPC)")
Rel(api, storage, "Uses")
Rel(api, email, "Notify")
Rel(web, auth, "Authenticates")
Rel(api, auth, "Authenticates")

@enduml
....


==== With Data Modelling Tool

[plantuml,,svg]
....
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
LAYOUT_WITH_LEGEND()

Container_Ext(auth, "Authentication","Azure AD Auth service")
Container_Ext(environment, "Environment Source", "")

Boundary(radix, "Radix", "Equinor PaaS"){
    Container(web, "WebApp", "React SPA", "Login with a role('Forcaster' or 'User') which grants different views")
    Container(api, "API", "Python rest API", "API for CRUD operations as well as scheduling SIMA tasks")
    Container_Ext(simaservice, "SIMA Runtime Service", "", "Azure AD Login with a role('Forcaster' or 'User') which grants different views")
}

Container_Ext(dmt, "Data Modelling Tool", "", "Used to create SIMA Tasks and models")
ContainerDb_Ext(dmss, "Data Modelling Storage Service", "", "Stores environments, models, and SIMA tasks")
Container_Ext(email, "Email Service", "","Used to notify users of completed long-running tasks")

Rel(environment, web, "Uploads")
Rel(web, api, "HTTP")
Rel(api, simaservice, "Starts tasks and fetches results (gRPC)")
Rel(api, dmss, "Uses")
Rel(api, email, "Notify")
Rel(dmt, dmss, "Backed by")
Rel(web, auth, "Authenticates")
Rel(api, auth, "Authenticates")

@enduml
....

== Meeting Logs

09.03.2021:

* Need implementation assistance on backend and frontend.
* Weekly should invite Rune and Tim.
* Synergy and usage of Data Modelling Tool (DMT).
** Hopefully DMT can be used, but not critical, the importance is to deliver working application.
