name: Checks

on: push

env:
  DOCKER_BUILDKIT: 1
  API_IMAGE: ghcr.io/equinor/for/api
  WEB_IMAGE: ghcr.io/equinor/for/web

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install pre-commit
        run: pip install pre-commit poetry && poetry config virtualenvs.in-project true

      - name: Create venv
        run: cd api && poetry install

      - name: Run pre-commit
        run: pre-commit run --all-files

  integration-tests-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Docker login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: "Pull latest"
        run: docker pull $API_IMAGE

      - name: "Build API test image"
        run: docker build --cache-from $API_IMAGE --target development --tag $API_IMAGE ./api

      - name: "API BDD Tests"
        run: docker-compose run api behave
